include:
- ./func/*
kind: ArchiveUploadSpec
name: func-Wfgl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: post-custody-route
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: post-custody-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-Wfgl
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-08-18T19:38:29Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: post-custody-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: post-custody-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.post_user_ticket
    packageref:
      name: post-custody-route
      namespace: default
  requestsPerPod: 1
  resources: {}
