apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 74b43def-38b9-4404-b094-ccb27eb45e86
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: post-custody-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ticket/custody_transfer
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /ticket/custody_transfer
