apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: post-custody-route
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: post-custody-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ticket/custody_transfer
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /ticket/custody_transfer
